### PR TITLE
Modified ignition and cv variables for Noetic/focal

### PR DESCRIPTION
**Pull request by crvogt**
Updated ignition and opencv variables to compile with Neotic/Focal/Gazebo11. Currently compiles, but python scripts are not found and thrusters fail.

Currently going through the migration guide

### CODE REVIEW

**Comment by M1chaelM** [comment]
Confirming:
* I can currently build this on Focal/Noetic/gz11.
* I see the Python script problems you mention.

Also, it looks like the changes to ignition are not compatible with the previous version and break the build on melodic. I'm guessing we'll need to use ifdefs to support both at once. Hopefully there's some clean way to organize these.

**Comment by crvogt** [comment]
Currently following a trail of Python syntax errors in an effort to get the example working. I figured we can clean up and organise once we know what needs to be changed.

**Comment by crvogt** [comment]
`uuv_dave.launch` now working with this branch and PR Field-Robotics-Lab/uuv_manipulators#2

My Noetic install seemed to be lacking `kdl_parser_py` which I installed with `apt-get install ros-noetic-kdl-parser-py`

Noting that `cpplint.py` utilises `xrange()` and needs to be changed to `range()`.

Still seeing errors during runtime. 
- An ongoing issue detailed here https://github.com/ros/geometry2/issues/467 
- A type mismatch in `arm.py`

**Comment by crvogt** [comment]
Added some `#if` statements. The issues in `uuv_simulator` are linked to gazebo versions. Adding `#if` statements where required seems to be canon looking at previous changes from pre-gazebo9

Code compiles and runs `uuv_dave.launch` in both Noetic/Gazebo11 and Melodic/Gazebo9 for me.

**Review by M1chaelM — APPROVED** [review]
Looks good to me! In combination with changes to `uuv_manipulators`, this is building and the `uuv_dave.launch` demo runs for me now in both melodic and noetic. I will approve PRs for both repos. I did also have to install `ros-noetic-kdl-parser-py`, so I will add this to the installation instructions.

**Pull request merged**
